version = 0.1
[default.deploy.parameters]
stack_name = "campus-explorer-api"
resolve_s3 = true
s3_prefix = "campus-explorer-api"
region = "us-east-1"
profile = "admin"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
