AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  campus-explorer-api
  Sample SAM Template for campus-explorer-api
Globals:
  Api:
    Cors:
      AllowOrigin: '''*'''
      AllowHeaders: '''Content-Type'''
  Function:
    Timeout: 3
Resources:
  PostImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: packages/campus-explorer-api-lib
      Handler: index.handlePostImageFunction
      Runtime: nodejs18.x
      Architectures:
        - x86_64
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - src/index.ts
Outputs:
  PostImageFunction:
    Description: PostImageFunction ARN
    Value: '!GetAtt PostImageFunction.Arn'
  PostImageFunctionIamRole:
    Description: Implicit IAM Role created for PostImageFunction
    Value: '!GetAtt PostImageFunctionRole.Arn'
