AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  campus-explorer-api
  Sample SAM Template for campus-explorer-api
Globals:
  Api:
    Cors:
      AllowOrigin: '''*'''
      AllowHeaders: '''Content-Type'''
  Function:
    Timeout: 3
Resources:
  PostImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: packages/campus-explorer-api-lib
      Handler: index.handlePostImageFunction
      Runtime: nodejs18.x
      Architectures:
        - x86_64
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - src/index.ts
  SubmittedImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
    OwnershipControls:
      Rules:
        - ObjectOwnership: ObjectWriter
  SubmittedImagesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: '!Ref SubmittedImagesBucket'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: '!Sub ''arn:aws:s3:::${SubmittedImagesBucket}/*'''
Outputs:
  PostImageFunction:
    Description: PostImageFunction ARN
    Value: '!GetAtt PostImageFunction.Arn'
  PostImageFunctionIamRole:
    Description: Implicit IAM Role created for PostImageFunction
    Value: '!GetAtt PostImageFunctionRole.Arn'
  SubmittedImagesBucketName:
    Description: Assigned name for SubmittedImagesBucket
    Value: '!Ref SubmittedImagesBucket'
  SubmittedImagesBucketArn:
    Description: SubmittedImagesBucket ARN
    Value: '!GetAtt SubmittedImagesBucket.Arn'
  SubmittedImagesBucketDomainName:
    Description: Domain name for SubmittedImagesBucket
    Value: '!GetAtt SubmittedImagesBucket.DomainName'
  SubmittedImagesBucketWebsiteURL:
    Description: WebsiteURL for SubmittedImagesBucket
    Value: '!GetAtt SubmittedImagesBucket.WebsiteURL'
